/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sistemaescritorio.apresentacao;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Miih Santos
 */
public class TelaInicialForm extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaInicialForm() {
        initComponents();
        DesabilitarFuncoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCliente = new javax.swing.JMenu();
        mnuItemCadastroCliente = new javax.swing.JMenuItem();
        mnuItemConsultaCliente = new javax.swing.JMenuItem();
        mnuFuncionario = new javax.swing.JMenu();
        mnuItemCadastroFuncionario = new javax.swing.JMenuItem();
        mnuItemConsultaFuncionario = new javax.swing.JMenuItem();
        mnuProcesso = new javax.swing.JMenu();
        mnuItemCadastroProcesso = new javax.swing.JMenuItem();
        mnuItemConsultaProcesso = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuRelatorio = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuSobre = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGEA - Tela Principal");
        setExtendedState(6);
        setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/4_Grayscale_logo_on_transparent_272x75.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        mnuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/1467369928_user-group.png"))); // NOI18N
        mnuCliente.setText("Clientes");

        mnuItemCadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/add_user.png"))); // NOI18N
        mnuItemCadastroCliente.setText("Cadastro");
        mnuItemCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(mnuItemCadastroCliente);

        mnuItemConsultaCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/search.png"))); // NOI18N
        mnuItemConsultaCliente.setText("Pesquisa");
        mnuItemConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConsultaClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(mnuItemConsultaCliente);

        jMenuBar1.add(mnuCliente);

        mnuFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/user.png"))); // NOI18N
        mnuFuncionario.setText("Funcionários");

        mnuItemCadastroFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/add_user.png"))); // NOI18N
        mnuItemCadastroFuncionario.setText("Cadastro");
        mnuItemCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionario.add(mnuItemCadastroFuncionario);

        mnuItemConsultaFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        mnuItemConsultaFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/1466829856_search_magnifying_glass_find.png"))); // NOI18N
        mnuItemConsultaFuncionario.setText("Consulta");
        mnuItemConsultaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConsultaFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionario.add(mnuItemConsultaFuncionario);

        jMenuBar1.add(mnuFuncionario);

        mnuProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/search102.png"))); // NOI18N
        mnuProcesso.setText("Processos");

        mnuItemCadastroProcesso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemCadastroProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/1469080825_File_add.png"))); // NOI18N
        mnuItemCadastroProcesso.setText("Cadastro");
        mnuItemCadastroProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroProcessoActionPerformed(evt);
            }
        });
        mnuProcesso.add(mnuItemCadastroProcesso);

        mnuItemConsultaProcesso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuItemConsultaProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/1466829856_search_magnifying_glass_find.png"))); // NOI18N
        mnuItemConsultaProcesso.setText("Consulta");
        mnuItemConsultaProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConsultaProcessoActionPerformed(evt);
            }
        });
        mnuProcesso.add(mnuItemConsultaProcesso);

        jMenuBar1.add(mnuProcesso);

        jMenu1.setText("Comarca");
        jMenuBar1.add(jMenu1);

        mnuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/1469081363_Paste.png"))); // NOI18N
        mnuRelatorio.setText("Relatórios");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Processos Encerrados");
        mnuRelatorio.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Processos em Andamento");
        mnuRelatorio.add(jMenuItem3);

        jMenuBar1.add(mnuRelatorio);

        mnuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/1469081340_Faq.png"))); // NOI18N
        mnuSobre.setText("Sobre");
        jMenuBar1.add(mnuSobre);

        mnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/sistemaescritorio/apresentacao/imagens/1469081327_Login_out.png"))); // NOI18N
        mnuSair.setText("Sair");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Sair do Sistema");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuSair.add(jMenuItem1);

        jMenuBar1.add(mnuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(667, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroClienteActionPerformed
        CadastroClienteForm cadastroClienteForm = new CadastroClienteForm();
        cadastroClienteForm.setVisible(true);
    }//GEN-LAST:event_mnuItemCadastroClienteActionPerformed

    private void mnuItemConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConsultaClienteActionPerformed
        ConsultaClienteForm consultaClienteForm = null;
        try {
            consultaClienteForm = new ConsultaClienteForm();
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        consultaClienteForm.setVisible(true);
    }//GEN-LAST:event_mnuItemConsultaClienteActionPerformed

    private void mnuItemCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroFuncionarioActionPerformed
        CadastroFuncionarioForm cadastroFuncionarioForm = new CadastroFuncionarioForm();
        cadastroFuncionarioForm.setVisible(true);
    }//GEN-LAST:event_mnuItemCadastroFuncionarioActionPerformed

    private void mnuItemConsultaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConsultaFuncionarioActionPerformed
        ConsultaFuncionarioForm consultaFuncionarioForm;
        try {
            consultaFuncionarioForm = new ConsultaFuncionarioForm();
            consultaFuncionarioForm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mnuItemConsultaFuncionarioActionPerformed

    private void mnuItemCadastroProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroProcessoActionPerformed
        CadastroProcessoForm cadastroProcessoForm = null;
        try {
            cadastroProcessoForm = new CadastroProcessoForm();
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        cadastroProcessoForm.setVisible(true);
    }//GEN-LAST:event_mnuItemCadastroProcessoActionPerformed

    private void mnuItemConsultaProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConsultaProcessoActionPerformed
        ConsultaProcessoForm consultaProcessoForm = null;
        try {
            consultaProcessoForm = new ConsultaProcessoForm();
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        consultaProcessoForm.setVisible(true);
    }//GEN-LAST:event_mnuItemConsultaProcessoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JMenu mnuCliente;
    private javax.swing.JMenu mnuFuncionario;
    private javax.swing.JMenuItem mnuItemCadastroCliente;
    private javax.swing.JMenuItem mnuItemCadastroFuncionario;
    private javax.swing.JMenuItem mnuItemCadastroProcesso;
    private javax.swing.JMenuItem mnuItemConsultaCliente;
    private javax.swing.JMenuItem mnuItemConsultaFuncionario;
    private javax.swing.JMenuItem mnuItemConsultaProcesso;
    private javax.swing.JMenu mnuProcesso;
    private javax.swing.JMenu mnuRelatorio;
    private javax.swing.JMenu mnuSair;
    private javax.swing.JMenu mnuSobre;
    // End of variables declaration//GEN-END:variables

    void habilitarFuncoesAdvogado() {
        mnuFuncionario.setEnabled(true);
        mnuProcesso.setEnabled(true);
        mnuCliente.setEnabled(true);
        
    }

    void DesabilitarFuncoes() {
        mnuFuncionario.setEnabled(false);
        mnuProcesso.setEnabled(false);
    }
}
